services:
  # Banco de Dados (Adicionado para funcionar localmente)
  db:
    image: postgres:15
    container_name: pg-grow
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=growtwitter
    ports:
      - "5433:5432"      #mudei de: 5432 para: 5433

  # Backend
  api:
    build: ./growtwitter-api
    container_name: backend-linkup
    ports:
      - "3000:3000"
    volumes:
      - ./growtwitter-api:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - ./growtwitter-api/.env
    environment:
      - NODE_ENV=development

  # Frontend
  web:
    build: ./linkUp
    container_name: frontend-linkup
    ports:
      - "5173:5173"
    volumes:
      - ./linkUp:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:3000

